---
abstract: 'A module to interact with Blue Coat SGOS-based devices.'
author:
  - 'Matthew Lange <mmlange@cpan.org>'
build_requires:
  TAP::Harness: '3.18'
  Test::More: '0'
  Test::NoWarnings: '1.04'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BlueCoat-SGOS
provides:
  BlueCoat::SGOS:
    file: lib/BlueCoat/SGOS.pm
    version: '1.06'
requires:
  Crypt::OpenSSL::X509: '1.804'
  Date::Parse: '0'
  DateTime: '0'
  English: '0'
  File::Map: '0'
  HTTP::Request: '6.00'
  LWP::Protocol::https: '6.06'
  LWP::UserAgent: '6.00'
  Readonly: '0'
  perl: v5.6.0
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
version: '1.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
